# Generated by Django 5.2.16 on 2026-09-18 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('collect_kind', models.CharField(blank=True, db_default='', max_length=64)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('water_depth_m', models.FloatField(blank=True, null=True)),
                ('collected_at', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('kpdc_id', models.CharField(blank=True, db_default='', max_length=32)),
                ('kpdc_meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '지점',
                'ordering': ['site', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(choices=[('ant', '남극')], db_default='ant', default='ant', max_length=8)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '지역',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('depth_cm', models.FloatField(blank=True, null=True)),
                ('dry_weight_g', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='viewer.locality')),
            ],
            options={
                'verbose_name': '시료',
                'ordering': ['locality', 'depth_cm', 'code'],
            },
        ),
        migrations.AddField(
            model_name='locality',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='viewer.site'),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('image_dir', models.CharField(max_length=500)),
                ('obs_no', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('obs_label', models.CharField(blank=True, db_default='', default='', max_length=10)),
                ('fraction_um', models.FloatField(blank=True, null=True)),
                ('split_denom', models.PositiveIntegerField(blank=True, null=True)),
                ('cells', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hide_in_list', models.BooleanField(db_default=False, default=False)),
                ('exclude_from_totals', models.BooleanField(db_default=False, default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('copying', 'copying'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='done', max_length=12)),
                ('state_note', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('copied_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='viewer.sample')),
            ],
            options={
                'verbose_name': '관찰',
                'ordering': ['sample', 'fraction_um', 'obs_no', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['locality', 'depth_cm'], name='viewer_samp_localit_55866c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('locality', 'code'), name='uniq_sample_code'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='uniq_locality_code'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['sample', 'obs_no'], name='viewer_slid_sample__ed9cac_idx'),
        ),
    ]
