# Generated by Django 5.2.16 on 2026-09-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='corr_thresh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('um_per_pixel', models.FloatField(blank=True, null=True)),
                ('um_per_pixel_source', models.CharField(blank=True, choices=[('leica', 'leica'), ('exif', 'exif'), ('toml', 'toml'), ('sidecar', 'sidecar'), ('default', 'default'), ('cli', 'cli')], max_length=8)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('sharpness', models.FloatField(blank=True, null=True)),
                ('is_sharpest', models.BooleanField(default=False)),
                ('seq', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='viewer.slide')),
            ],
            options={
                'ordering': ['slide', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='RunBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('group', 'group'), ('stack', 'stack'), ('detect', 'detect'), ('classify', 'classify'), ('refilter', 'refilter'), ('reconcile', 'reconcile'), ('ingest', 'ingest'), ('export', 'export')], max_length=16)),
                ('label', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('for_review', models.BooleanField(db_default=False, default=False)),
                ('recipe', models.JSONField(blank=True, db_default={}, default=dict)),
                ('code', models.CharField(blank=True, db_default='', default='', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'label'), name='uniq_batch_label'), models.UniqueConstraint(condition=models.Q(('for_review', True)), fields=('for_review',), name='uniq_batch_for_review'), models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='uniq_batch_code'), models.CheckConstraint(condition=models.Q(('code__in', ['M', 'm']), _negated=True), name='batch_code_not_manual')],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('group', 'group'), ('stack', 'stack'), ('detect', 'detect'), ('classify', 'classify'), ('refilter', 'refilter'), ('reconcile', 'reconcile'), ('ingest', 'ingest'), ('export', 'export')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('done', 'done'), ('partial', 'partial'), ('failed', 'failed')], default='running', max_length=8)),
                ('error', models.TextField(blank=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('host', models.CharField(blank=True, max_length=64)),
                ('gpu', models.CharField(blank=True, max_length=64)),
                ('code_version', models.CharField(blank=True, max_length=64)),
                ('slide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='viewer.slide')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='viewer.runbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Viewpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('tag', models.CharField(max_length=120)),
                ('cell', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('n_frames', models.IntegerField(default=0)),
                ('span_sec', models.FloatField(blank=True, null=True)),
                ('grouping_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewpoints', to='viewer.run')),
                ('sharpest_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharpest_of', to='viewer.frame')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewpoints', to='viewer.slide')),
            ],
            options={
                'ordering': ['slide', 'idx'],
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focused_path', models.CharField(max_length=500)),
                ('depth_path', models.CharField(blank=True, max_length=500)),
                ('depth_npz_path', models.CharField(blank=True, max_length=500)),
                ('um_per_pixel', models.FloatField(blank=True, null=True)),
                ('native_um_per_pixel', models.FloatField(blank=True, null=True)),
                ('resize_scale', models.FloatField(default=1.0)),
                ('um_per_pixel_source', models.CharField(blank=True, max_length=8)),
                ('align_failed', models.IntegerField(default=0)),
                ('object_px_frac', models.FloatField(blank=True, null=True)),
                ('sharpness_best_single', models.FloatField(blank=True, null=True)),
                ('sharpness_fused', models.FloatField(blank=True, null=True)),
                ('gain', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_of', to='viewer.frame')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stacks', to='viewer.run')),
                ('viewpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stack', to='viewer.viewpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stack', '합성본'), ('frame', '프레임'), ('depth', '깊이맵')], max_length=8)),
                ('path', models.CharField(max_length=500, unique=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='viewer.frame')),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewer.stack')),
                ('viewpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='viewer.viewpoint')),
            ],
            options={
                'ordering': ['viewpoint', 'kind', 'path'],
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='viewpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frames', to='viewer.viewpoint'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['kind', '-started_at'], name='viewer_run_kind_0bf9e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='viewpoint',
            constraint=models.UniqueConstraint(fields=('slide', 'idx'), name='uniq_viewpoint_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['viewpoint', 'kind'], name='viewer_imag_viewpoi_4a205e_idx'),
        ),
        migrations.AddConstraint(
            model_name='frame',
            constraint=models.UniqueConstraint(fields=('slide', 'name'), name='uniq_frame_name'),
        ),
    ]
