# Generated by Django 5.2.16 on 2026-09-18 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_runs_viewpoints_frames_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('short', models.CharField(blank=True, max_length=16)),
                ('badge', models.CharField(blank=True, max_length=16)),
                ('color', models.CharField(blank=True, max_length=24)),
                ('is_taxon', models.BooleanField(default=False)),
                ('counted', models.BooleanField(default=True)),
                ('hotkey', models.CharField(blank=True, max_length=8)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('min_um', models.FloatField(default=63.0)),
                ('max_um', models.FloatField(default=2000.0)),
                ('conf_min', models.FloatField(default=0.25)),
                ('is_default', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('scale', models.FloatField(default=1.0)),
                ('um_per_pixel', models.FloatField(blank=True, null=True)),
                ('um_per_pixel_native', models.FloatField(blank=True, null=True)),
                ('um_per_pixel_source', models.CharField(blank=True, max_length=8)),
                ('um_per_pixel_backfilled', models.BooleanField(default=False)),
                ('n_raw_masks', models.IntegerField(default=0)),
                ('n_sized', models.IntegerField(default=0)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='viewer.image')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='viewer.run')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='viewer.detection')),
                ('viewpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='viewer.viewpoint')),
                ('thresholds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='viewer.thresholdset')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_key', models.CharField(max_length=64)),
                ('raw_id', models.IntegerField(blank=True, null=True)),
                ('bbox_x', models.IntegerField()),
                ('bbox_y', models.IntegerField()),
                ('bbox_w', models.IntegerField()),
                ('bbox_h', models.IntegerField()),
                ('center_x', models.IntegerField(blank=True, null=True)),
                ('center_y', models.IntegerField(blank=True, null=True)),
                ('area_px', models.IntegerField(default=0)),
                ('area_um2', models.FloatField(blank=True, null=True)),
                ('major_um', models.FloatField(blank=True, null=True)),
                ('minor_um', models.FloatField(blank=True, null=True)),
                ('long_side_um', models.FloatField(blank=True, null=True)),
                ('short_side_um', models.FloatField(blank=True, null=True)),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('fill_ratio', models.FloatField(blank=True, null=True)),
                ('shape_ok', models.BooleanField(default=False)),
                ('circularity', models.FloatField(blank=True, null=True)),
                ('convexity', models.FloatField(blank=True, null=True)),
                ('solidity', models.FloatField(blank=True, null=True)),
                ('elongation', models.FloatField(blank=True, null=True)),
                ('ellipse_iou', models.FloatField(blank=True, null=True)),
                ('texture', models.FloatField(blank=True, null=True)),
                ('predicted_iou', models.FloatField(blank=True, null=True)),
                ('stability_score', models.FloatField(blank=True, null=True)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('passed', models.BooleanField(default=False)),
                ('cls', models.CharField(blank=True, max_length=32)),
                ('reject', models.CharField(blank=True, max_length=64)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='viewer.detection')),
            ],
            options={
                'indexes': [models.Index(fields=['detection', 'passed'], name='viewer_cand_detecti_226e04_idx'), models.Index(fields=['cls'], name='viewer_cand_cls_1b125a_idx'), models.Index(fields=['major_um'], name='viewer_cand_major_u_fdd08c_idx'), models.Index(fields=['texture'], name='viewer_cand_texture_c05a8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('detection', 'mask_key'), name='uniq_candidate_key')],
            },
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['viewpoint', 'is_current'], name='viewer_dete_viewpoi_62828b_idx'),
        ),
    ]
