# Generated by Django 5.2.16 on 2026-09-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_seed_classdef'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForamObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=32)),
                ('pose', models.CharField(blank=True, choices=[('umbilical', 'umbilical view'), ('spiral', 'spiral view'), ('edge', 'edge view'), ('apertural', 'apertural view'), ('other', 'other position')], db_default='', default='', max_length=10)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A — 동정키도 완형도 잘 드러난다'), ('B', 'B — 완형이나 형태가 덜 드러난다 · 또는 상태가 나쁘나 동정키가 남았다'), ('C', 'C — 완형도 동정키도 잘 안 드러난다')], db_default='', default='', max_length=1)),
                ('note', models.TextField(blank=True, db_default='', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foram_objects', to='viewer.runbatch')),
                ('viewpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foram_objects', to='viewer.viewpoint')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_key', models.CharField(max_length=64)),
                ('bind_method', models.CharField(choices=[('exact', 'exact'), ('iou', 'iou'), ('manual', 'manual'), ('orphan', 'orphan')], default='orphan', max_length=8)),
                ('bind_score', models.FloatField(blank=True, null=True)),
                ('geom', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('engine', 'engine'), ('manual', 'manual')], db_default='engine', default='engine', max_length=8)),
                ('geom_edited', models.BooleanField(db_default=False, default=False)),
                ('is_rep', models.BooleanField(db_default=False, default=False)),
                ('removed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('auto_confirmed', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='object_reviews', to='viewer.runbatch')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='viewer.candidate')),
                ('foram_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='viewer.foramobject')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_reviews', to='viewer.image')),
                ('viewpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_reviews', to='viewer.viewpoint')),
            ],
        ),
        migrations.AddField(
            model_name='foramobject',
            name='anchor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchor_of', to='viewer.objectreview'),
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('rank', models.CharField(blank=True, choices=[('Phylum', 'Phylum'), ('Subphylum', 'Subphylum'), ('Class', 'Class'), ('Subclass', 'Subclass'), ('Order', 'Order'), ('Suborder', 'Suborder'), ('Superfamily', 'Superfamily'), ('Family', 'Family'), ('Subfamily', 'Subfamily'), ('Genus', 'Genus'), ('Subgenus', 'Subgenus'), ('Species', 'Species'), ('Subspecies', 'Subspecies'), ('Variety', 'Variety'), ('Forma', 'Forma')], max_length=16)),
                ('aphia_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(db_default='accepted', default='accepted', max_length=40)),
                ('authority', models.CharField(blank=True, db_default='', default='', max_length=160)),
                ('habit', models.CharField(blank=True, choices=[('', '—'), ('planktonic', '부유성'), ('benthic', '저서성')], db_default='', default='', max_length=12)),
                ('active', models.BooleanField(db_default=False, default=False)),
                ('extinct', models.BooleanField(db_default=False, default=False)),
                ('note', models.TextField(blank=True, db_default='', default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonyms', to='viewer.taxon')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='viewer.taxon')),
            ],
            options={
                'verbose_name_plural': 'taxa',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='foramobject',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foram_objects', to='viewer.taxon'),
        ),
        migrations.CreateModel(
            name='ViewpointReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viewpoint_reviews', to='viewer.runbatch')),
                ('viewpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='viewer.viewpoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='objectreview',
            index=models.Index(fields=['viewpoint', 'bind_method'], name='viewer_obje_viewpoi_fcb0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='objectreview',
            index=models.Index(fields=['bind_method'], name='viewer_obje_bind_me_cdbbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='objectreview',
            index=models.Index(fields=['image', 'batch'], name='viewer_obje_image_i_c20d93_idx'),
        ),
        migrations.AddIndex(
            model_name='objectreview',
            index=models.Index(fields=['source'], name='viewer_obje_source_4be8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='objectreview',
            index=models.Index(fields=['foram_object'], name='viewer_obje_foram_o_a77c13_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectreview',
            constraint=models.UniqueConstraint(fields=('foram_object', 'image'), name='uniq_objreview_object_image'),
        ),
        migrations.AddConstraint(
            model_name='objectreview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_rep', True)), fields=('foram_object',), name='uniq_objreview_rep'),
        ),
        migrations.AddConstraint(
            model_name='objectreview',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('image', 'batch', 'mask_key'), name='uniq_objreview_key'),
        ),
        migrations.AddConstraint(
            model_name='objectreview',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('image', 'mask_key'), name='uniq_objreview_manual'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['active', 'name'], name='viewer_taxo_active_3c0ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['rank'], name='viewer_taxo_rank_734b8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxon',
            constraint=models.UniqueConstraint(fields=('name', 'authority'), name='uniq_taxon_name_authority'),
        ),
        migrations.AddIndex(
            model_name='foramobject',
            index=models.Index(fields=['viewpoint'], name='viewer_fora_viewpoi_af6a49_idx'),
        ),
        migrations.AddIndex(
            model_name='foramobject',
            index=models.Index(fields=['viewpoint', 'batch'], name='viewer_fora_viewpoi_e9e63f_idx'),
        ),
        migrations.AddIndex(
            model_name='foramobject',
            index=models.Index(fields=['taxon'], name='viewer_fora_taxon_i_7ce1eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='viewpointreview',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('viewpoint', 'batch'), name='uniq_vpreview_batch'),
        ),
        migrations.AddConstraint(
            model_name='viewpointreview',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('viewpoint',), name='uniq_vpreview_note'),
        ),
    ]
